### PR TITLE
Added attribs to Anime object. Updated tests.

### PR DESCRIPTION
**Pull request by donniebishop**
Added support for some new attributes and information provided by the API. Other objects looked mostly fine, it just looked like the Anime object needed some updating.

Tests were being mean for having like 4 new titles for Eva, so I added those into the the test assertion as well.

### CODE REVIEW

**Comment by KnightHawk3** [comment]
Looks good to me, shame I don't have time / passion for this at the moment.

Would you like to become a contributor?

**Comment by donniebishop** [comment]
Wouldn't mind at all. There's some things I missed, I think with getting user feeds and all, and wouldn't mind helping maintain this. 

Working on a Hummingbird CLI client, and this wrapper has been a great help in moving things along, so I'd like to give back if I can.

**Comment by KnightHawk3** [comment]
Commit responsibly :)

**Comment by donniebishop** [comment]
Haha will do. 

Do you wanna push this out to pypi, or do you want to wait for me to work on integrating some of the newer endpoints?

**Comment by KnightHawk3** [comment]
Sure, but I will let you, whats your PyPi username?

**Comment by donniebishop** [comment]
Never actually pushed to PyPI before, so this will be an interesting new experience :sweat_smile: 

Just signed up. Username is donniebishop

Any particular tips or things to note before pushing out an update?

**Comment by KnightHawk3** [comment]
Nah, just try not to mess it up ;)

Let me know if you need help.

**Comment by donniebishop** [comment]
Aaaand Hummingbird v0.0.3 is now live on PyPI. All with minimal damage to myself, others, and the general interwebs

**Pull request merged**
